version: '3.8'
services:
  postgres: 
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypass
  
  user-app:
    build:
      network: host
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      - postgres
        # condition: service_completed_successfully

    environment:
      DATABASE_URL: postgresql://postgres:mypass@postgres:5432/postgres